# SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "cuvs"
description = "RAPIDS cuVS — GPU-accelerated vector search"
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
license.workspace = true
build = "build.rs"

[features]
ndarray = ["dep:ndarray"]
torch = ["dep:tch", "dep:torch-sys"]

[dependencies]
cuvs-sys.workspace = true
ndarray = { version = "0.17", optional = true }
tch = { version = "0.24", optional = true }
torch-sys = { version = "0.24", optional = true }
thiserror = "2"
tinyvec = { version = "1", features = ["latest_stable_rust"] }
bon = "3.9.1"
ordered-float = { version = "5.3.0", default-features = false }

[[example]]
name = "cagra"
required-features = ["torch"]
